import = ["/home/deanqx/.config/alacritty/dracula.toml"]

[window]
opacity = 0.85 # comment

[env]
TERM = "xterm-256color" # Test comment

[shell]
program = "/bin/zsh"
args = ["--login"]

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ScrollPageUp"
mods = "Control"
key = "Up"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "Down"
mods = "Control"
