[window]
opacity = 0.92

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ScrollPageUp"
mods = "Control"
key = "Up"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "Down"
mods = "Control"

[general]
import = ["/home/deanqx/.config/alacritty/dracula.toml"]

[terminal]
